[project]
name = 'local-library-sharing'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.lending-tracking]
path = 'contracts/lending-tracking.clar'
clarity_version = 3
epoch = 3.1

[contracts.resource-catalog]
path = 'contracts/resource-catalog.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
